### PR TITLE
Gamemodule source

### PR DESCRIPTION
**Pull request by zolero**
Hello folks,
I have decompiled the jar files and syntax errors. This might be useful for gameserver changes.
Could some people review this.

### CODE REVIEW

**Comment by IcyPalm** [comment]
Could you move the modules to `nl.hanze.t23i.gamemodule.extern.[modulename]` for easier packaging

**Comment by goto-bus-stop** [comment]
If they're going to be packaged as separate jars, this should work just fine, I think(?)

**Comment by goto-bus-stop** [comment]
Otherwise we have to manually exclude the modules from the main server package.

**Comment by IcyPalm** [comment]
I was working on packaging for the nl.hanze.gameserver and seperate for the nl.hanze.t23i but you are right, this could work as well

**Comment by IcyPalm** [comment]
This closes #8 and #9 when merged

**Comment by IcyPalm** [comment]
After a bit of searching here the Maven docs for creating multiple `.jar`s 
Maybe somebody could look into this, otherwise I am going to do that tomorrow

**Comment by zolero** [comment]
It's at the right package folder now?

**Pull request merged**
