### PR TITLE
Added Gamemodules folder including Reversi / Tic-Tac-Toe modules.

### PR DESCRIPTION
**Pull request by Rkallenkoot**
Tic-Tac-Toe and Reversi (Othello) gamemodules

### CODE REVIEW

**Comment by IcyPalm** [comment]
I am going to deny this pull request based on the fact that there is no source included in this. I guess you have written these modules so can we please see the source for this.

@goto-bus-stop

**Comment by Rkallenkoot** [comment]
Oke

**Comment by goto-bus-stop** [comment]
What's the plan? Merge now & rewrite later?

**Comment by IcyPalm** [comment]
Seems like the plan atm, yes @goto-bus-stop

**Comment by goto-bus-stop** [comment]
OK. then this likely has some way of formatting moves already, so we can just follow whatever these modules do for #12.

**Comment by IcyPalm** [comment]
Merge? @goto-bus-stop

**Pull request merged**
